travis:
  secure:
    BINSTAR_TOKEN: cyQYScasjfpG6SLMKVQlLc0DuW0qIcyAOvXI89TF1PwZpzkXwdFFxQZONNHeDa/YmLF/BMHvjBYeJjVBeazy3IYKFxP9ZD+nVXZg0EmNxpHwqh1/z3uwhSNBgosTZCsZRFmHHEp6q035KeVd9FxIfuL+SZA/1YTs9zsEdzHpzNTqnZ6oyZlG9pprWPupBpiSLeQlZCKdzP34wMXXEx3gvIWNnp6q5+TasVcXrhTnLxakLzJuGkvGh9N9oDJ+yd/YpMfMTWTIWTCBhzF0FbGFPclpLi1P8F4hqt/xSnTpGAhC6oRvqkZpiYkOjL5lMjwUehypZq452pB+NQiYYUk4x8htcnSsZja8vGqeRY16eXLvTiUUoX7WFuPEmfN0e2Rag0w3BAvALFX0Qp+yDbgiP/bpphLAB/Nzn//OlyuIJQSjWLWxH3ezkhSlHMZS2jMMKuHXUBrhYbhF/TN8JkXiC4HEQDvco7cXwCIwAd2gE7FGwkx3F+Q4/dSF+dEqsDjFKjEGf2if9XmYnwIMvoLGipZcfVox3oG6IMUnMVIFKIg/suRCN1Md3ntWn1+zDTalwFMGJgok636biSgx/bIx1O0I6qwFMVCPzbu1Jr6KqJO59TZDwq2beU2RzTNtKJCzuOSTgSqHRIGo2vq58rVLEAPqEUVDFBxQzMWBSZvbgj8=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
